version: "3"

services:
    postgres:
        image: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${PG_DBNAME}
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}

volumes: 
    pgdata: